name: ðŸ§® Minimal GitHub Metrics

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate minimal GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: DHANUSH1323

          # Output setup
          filename: github-metrics.svg
          output_action: commit

          # Timezone
          config_timezone: America/New_York

          # Minimal template
          template: classic
          base: ""
          config_display: large

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_streak: yes
          plugin_streak_display: yes
          plugin_streak_days: 365
          plugin_streak_full_year: yes
          plugin_streak_sections: current, longest
