name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # update every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: DHANUSH1323
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_streak: yes
          plugin_streak_days: 365
          plugin_streak_threshold: 1
