name: GitHub Streak Stats

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate streak-only metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: DHANUSH1323

          
          filename: github-streaks.svg
          output_action: commit

          
          template: classic
          config_timezone: America/New_York
          config_display: large

          
          base: ""
          
          plugin_streak: yes
          plugin_streak_display: yes
          plugin_streak_sections: current, longest
          plugin_streak_days: 365
          plugin_streak_full_year: yes

          
          config_twemoji: yes
          config_order: streak
          config_padding: 16
          config_layout: horizontal
