name: GitHub Streak Summary

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate clean streak summary
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: DHANUSH1323
          filename: github-streaks.svg
          output_action: commit

          template: classic
          config_timezone: America/New_York
          config_display: large
          base: header

          plugin_streak: yes
          plugin_streak_days: 365
          plugin_streak_full_year: yes
          plugin_streak_sections: current, longest

          
          plugin_isocalendar: no
          plugin_languages: no
          plugin_repositories: no

          
          config_twemoji: yes
          config_padding: 24
          config_layout: horizontal
          config_order: base, streak
